import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','Processing','WeightedL1')
files = ['GulfOfSuez.mat']
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
#        Fetch(os.path.join('data',elm),loc,FTPserver)


