import os
from rsf.proj import *

################
# RETRIEVE DATA
################

# Define SLIM FTP server information
FTPserver = {
             'server': 'ftp.slim.gatech.edu',
             'login': 'ftp',
             'password':''}

loc = os.path.join('SoftwareRelease','Common','GulfOfSuez')
files = ['GulfOfSuez178.su', 'SuezShots125.355shots.su']


# Fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)



