import os
from rsf.proj import *

################
# RETRIEVE DATA
################

# Define SLIM FTP server information
FTPserver = {
             'server': 'ftp.slim.gatech.edu',
             'login': 'ftp',
             'password':''}

loc = os.path.join('SoftwareRelease','Processing','SparsityPromotingDenoising','Data')
files = ['FreqInd30_DG.rsf','FreqInd44_DG.rsf','FreqInd59_DG.rsf']


# Fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

End()

