import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','Imaging','L1MIGRATIONwVP','data')
files = ['data.mat','model.mat','data_iwave_f.mat','LinearData.mat','sigsbee_nosalt_model.mat','preproc_iwave_FDData.mat','preproc_FDdata.mat']

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
