%% set environment
curdir = pwd;
projdir = [pwd,'/../..'];
datadir = [projdir,'/data'];
resultdir = [projdir,'/results/saltdome'];

%% i/o related
Q_file = [datadir,'/nosparsity_oblique_data.mat'];
model_bg_file = [datadir, '/vel_bg_saltdome_mini_slowness2.mat'];
input_data_file = [datadir,'/linear_data_FullAcq_IP_alpha04.mat'];

%% inversion
rng('default')

Migration_with_SRM(...
    'vel_bg',model_bg_file,...
    'unit_vel','m/s',...
    'runRTM','1',...
    'RTM_file_name','RTM_IgnoreMul_FullAcq.mat',...
    'separate_input',1,...
    'input_data',input_data_file,...
    'data_variable_name','totaldata_linear',...
    'input_point_source',Q_file,...
    'Q_variable_name','q_est',...
    'length_boundary',200,...
    'results_folder',resultdir,...
    'preview_folder',resultdir,...
    'wavelet_type','IP',...
    'src_polarity','di',...
    'TukeyWin_alpha',0.4,...
    'taper_low_freq',0,...
    'data_type',4,...
    'source_type',2,...
    'use_oblique',1,...
    'dt',0.004,...
    'nt',512,...
    'dx',5,...
    'dz',5,...
    'nx',448,...
    'nz',251,...
    'x_rcv_grid',0:15:2235,...
    'z_rcv_grid',5,...
    'x_src_grid',0:15:2235,...
    'z_src_grid',5,...
    'x_src',0:15:2235,...
    'freq_upper',60);