import os
from rsf.proj import *

################
# RETRIEVE DATA
################

# Define SLIM FTP server information
FTPserver = {
             'server': 'ftp.slim.gatech.edu',
             'login': 'ftp',
             'password':''}

loc = os.path.join('SoftwareRelease','Acquisition','TimeLapseJRM','data')
files = ['data_4D.mat', 'time-lapse-data.mat']


# Fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

End()

