import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','Processing','LargeScaleLRI','data')
files = [ 'bgdata_freq75.mat']

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)	
