#!/bin/bash
function fail()
{
echo FATALL ERRROR in $1 stage
echo ... check output log
exit 1
}

if [ -n "$SLIM_APPS" ]; then
	echo Compiling MEX in $SLIM_APPS
else
	echo FATAL ERROR: undefined environment SLIM_APPS
	exit 1
fi

# TMPDIR
export TMPDIR=/tmp/`whoami`/MEX

# set prompt
PS4="\n%%%%% "
#set -x

# create new temporary directories
mkdir -p $TMPDIR || exit 1

# check for mex
echo CHECK mex stage
echo ... output in ${TMPDIR}/check_mex.log
mex -help 2>&1 | tee ${TMPDIR}/check_mex.log | cut -c 1-3 | grep 'MEX' || fail "CHECK for mex"
LDEXT=mexa64
echo CHECK mex done

# MEX SPGL1-SLIM
cd $SLIM_APPS/tools/solvers/SPGL1-SLIM/private || exit 1
echo MEX SPGL1-SLIM stage in `pwd`
echo ... output in ${TMPDIR}/SPGL1-SLIM
if newer oneProjectorMex.c oneProjectorCore.c heap.c oneProjectorMex.$LDEXT; then
    mex oneProjectorMex.c oneProjectorCore.c heap.c -output oneProjectorMex -DNDEBUG 1>${TMPDIR}/SPGL1-SLIM 2>&1 || fail "MEX SPGL1-SLIM"
fi
echo MEX SPGL1-SLIM done

# MEX GenSPGL1
cd $SLIM_APPS/tools/solvers/GenSPGL1/private || exit 1
echo MEX GenSPGL1 stage in `pwd`
echo ... output in ${TMPDIR}/GenSPGL1
if newer oneProjectorMex.c oneProjectorCore.c heap.c oneProjectorMex.$LDEXT; then
    mex oneProjectorMex.c oneProjectorCore.c heap.c -output oneProjectorMex -DNDEBUG 1>${TMPDIR}/GenSPGL1 2>&1 || fail "MEX GenSPGL1"
fi
echo MEX GenSPGL1 done

# MEX HTOpt
cd $SLIM_APPS/tools/solvers/HTOpt/objective || exit 1
echo MEX HTopt stage in `pwd`
if newer mxlsmisfitht.c mxlsmisfitht.$LDEXT; then
    mex mxlsmisfitht.c CFLAGS="-std=c99 -fPIC"
fi
echo MEX HTopt done

# MEX SPOT-SLIM
cd $SLIM_APPS/tools/utilities/SPOT-SLIM/+spot/+rwt/ || exit 1
echo MEX SPOT-SLIM stage in `pwd`
echo ... output in ${TMPDIR}/SPOT-SLIM
for f in mdwt midwt mrdwt mirdwt
do
    if newer $f.c $f.$LDEXT; then
        mex $f.c 1>${TMPDIR}/SPOT-SLIM 2>&1 || fail "MEX SPOT-SLIM"
    fi
done
echo MEX SPOT-SLIM done

# MEX 3DFreqModeling
cd $SLIM_APPS/tools/algorithms/3DFreqModeling/
echo MEX 3DFreqModeling stage in `pwd`
echo ... output in ${TMPDIR}/3DFreqModeling
if newer Hmvp_MT_mex.c Hmvp_MT_mex.$LDEXT; then
    mex -O CFLAGS='$CFLAGS -Wall -fopenmp -std=c99' LDFLAGS='$LDFLAGS -fopenmp' Hmvp_MT_mex.c 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer sweep_MT_mex.c sweep_MT_mex.$LDEXT; then
    mex CFLAGS='$CFLAGS -Wall -pthread -fopenmp -std=c99' \
	    COPTIMFLAGS='$COPTIMFLAGS -O2' \
	    CDEBUGFLAGS='$CDEBUGFLAGS -O' \
	    LDDEBUGFLAGS='$LDDEBUGFLAGS -O' \
	    LDOPTIMFLAGS='$LDOPTIMFLAGS -O2' \
	    LDFLAGS='$LDFLAGS -Wall -fopenmp' \
	    -largeArrayDims -lmwblas \
	    sweep_MT_mex.c 1>${TMPDIR}/Krylov 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_forw_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -output Helm3dmvp_forw_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_forw_wnc_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -DWNCMPLX -output Helm3dmvp_forw_wnc_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_forw_deriv_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -DDERIV -output Helm3dmvp_forw_deriv_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_adj_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -DADJ -output Helm3dmvp_adj_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_adj_wnc_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -DADJ -DWNCMPLX -output Helm3dmvp_adj_wnc_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
if newer Helm3dmvp_mex.c Helm3dmvp_adj_deriv_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dmvp_mex.c -DADJ -DDERIV -output Helm3dmvp_adj_deriv_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"    
fi
if newer Helm3dkaczswp_mex.c Helm3d_kacz_sweep_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dkaczswp_mex.c -output Helm3d_kacz_sweep_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"    
fi
if newer Helm3dkaczswp_mex.c Helm3d_kacz_sweep_wnc_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dkaczswp_mex.c -DWNCMPLEX -output Helm3d_kacz_sweep_wnc_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"    
fi
if newer Helm3dkaczswp_mex.c Helm3d_kacz_sweep_adj_mex.$LDEXT; then
    mex -largeArrayDims -lmwblas CFLAGS='$CFLAGS -fopenmp -std=c99 -O3' LDFLAGS='$LDFLAGS -fopenmp' Helm3dkaczswp_mex.c -DADJ -output Helm3d_kacz_sweep_adj_mex 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"    
fi

cd old_functions
if newer Hmvp_mex.c Hmvp_mex.$LDEXT; then
    mex Hmvp_mex.c 1>${TMPDIR}/3DFreqModeling 2>&1 || fail "MEX 3DFreqModeling"
fi
cd ..
echo MEX 3DFreqModeling done

# MEX Krylov
cd $SLIM_APPS/tools/solvers/Krylov/
echo MEX Krylov stage in `pwd`
echo ... output in ${TMPDIR}/Krylov
cd mtimesx_20110223
# blas_lib = 'the_actual_path_and_name_of_your_systems_BLAS_library'
# mex('-DDEFINEUNIX','mtimesx.c',blas_lib)
# mex('-DDEFINEUNIX','-largeArrayDims','mtimesx.c',blas_lib)
if newer mtimesx.c mtimesx_RealTimesReal.c mtimesx.$LDEXT; then
    mex CFLAGS='-DDEFINEUNIX -fPIC' \
        -largeArrayDims -lmwblas \
        mtimesx.c 1>${TMPDIR}/Krylov 2>&1 || fail "MEX Krylov"
fi
echo MEX Krylov done

# MEX old Krylov
cd $SLIM_APPS/tools/deprecated/solvers/Krylov
echo MEX old Krylov stage in `pwd`
echo ... output in ${TMPDIR}/oldKrylov
if newer sweepR_mex.c sweepR_mex.$LDEXT; then
    mex CFLAGS='$CFLAGS -Wall -pthread -std=c99' \
	    COPTIMFLAGS='$COPTIMFLAGS -O2' \
	    CDEBUGFLAGS='$CDEBUGFLAGS -O' \
	    LDDEBUGFLAGS='$LDDEBUGFLAGS -O' \
	    LDOPTIMFLAGS='$LDOPTIMFLAGS -O2' \
	    LDFLAGS='$LDFLAGS -Wall' \
	    -largeArrayDims -lmwblas \
	    sweepR_mex.c 1>${TMPDIR}/oldKrylov 2>&1 || fail "MEX old Krylov"
fi
if newer sweep_MT_mex_old.c sweep_MT_mex_old.$LDEXT; then
    mex CFLAGS='$CFLAGS -Wall -pthread -std=c99' \
	    COPTIMFLAGS='$COPTIMFLAGS -O2' \
	    CDEBUGFLAGS='$CDEBUGFLAGS -O' \
	    LDDEBUGFLAGS='$LDDEBUGFLAGS -O' \
	    LDOPTIMFLAGS='$LDOPTIMFLAGS -O2' \
	    LDFLAGS='$LDFLAGS -Wall' \
	    -largeArrayDims -lmwblas \
	    sweep_MT_mex_old.c 1>${TMPDIR}/oldKrylov 2>&1 || fail "MEX old Krylov"
fi
echo MEX old Krylov done

# MEX QuasiNewton
cd $SLIM_APPS/tools/solvers/QuasiNewton/minConf_mod/minFunc || exit 1
echo MEX QuasiNewton stage in `pwd`
echo ... output in ${TMPDIR}/QuasiNewton
if newer lbfgsC.c lbfgsC.$LDEXT; then
    mex lbfgsC.c 1>${TMPDIR}/QuasiNewton 2>&1 || fail "MEX QuasiNewton"
fi
echo MEX QuasiNewton done

# clean temporary directories
echo CLEANUP stage
rm -rf $TMPDIR

echo MEX compilations completed
