#!/usr/bin/env python2.7
# simple command to test if source files are newer then target file (last on CL)
import os
import sys
import stat

dbg = False

if dbg: print "arguments:", len(sys.argv), sys.argv
if len(sys.argv) < 3:
    print 'FATAL ERROR in newer: not enough arguments'
    sys.exit(1)

sources = sys.argv[1:-1]
target = sys.argv[-1]
if dbg: print "sources: ", sources
if dbg: print "target:  ", target

if not os.path.exists(target):
    if dbg: print "target %s does not exist" % target
    sys.exit(0)
else:
    if dbg: print "target %s exists" % target

target_t = os.stat(target).st_mtime
if dbg: print "target %s mtime %f" % (target,target_t)

for src in sources:
    if not os.path.exists(src):
        print 'FATAL ERROR in newer: source %s does not exist' % src
        sys.exit(1)
    src_t = os.stat(src).st_mtime
    if dbg: print "source %s mtime %f / offset %f" % (src,src_t,src_t-target_t)
    if src_t > target_t: sys.exit(0)
sys.exit(1)

