import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','WaveformInversion','UQforWRI','data')
files = ['Ini_Vel.mat', 'SigmaD.mat', 'SimpleLayerData.mat', 'SimpleLayerkm.mat']
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
