import os
from rsf.proj import *

################
# RETRIEVE DATA
################

# Define SLIM FTP server information
FTPserver = {
             'server': 'ftp.slim.gatech.edu',
             'login': 'ftp',
             'password':''}

loc = os.path.join('SoftwareRelease','Acquisition','SourceSeparationL1','Original')
files = ['blended_data.rsf', 'blended_data_FRS.rsf', 'tdelay_src1.rsf', 'tdelay_src2.rsf', 'shifted_src1.rsf', 'shifted_src2.rsf', 'shifted_src1_FRS.rsf', 'shifted_src2_FRS.rsf']


# Fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

End()

