import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','WaveformInversion','3DParallelBatching','data')
files = ['overthrust_small-data-freq-3.rsf','overthrust_small-data-freq-4.rsf','overthrust_small-data-freq-5.rsf','overthrust_small-data-freq-6.rsf'];
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
