import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','Imaging','L1MIGRATIONwSRM','data')
files = ['nosparsity_oblique_data.mat','vel_bg_saltdome_mini_slowness2.mat','vel_true_saltdome_mini_slowness2.mat','linear_data_FullAcq_IP_alpha04.mat','preproc_iwave_FDData.mat','sigsbee_nosalt_model.mat','EPSI3_iwave_FDData.mat','sigsbee_nosalt_model_KinemWrongUnder2X.mat']

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
