import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','WaveformInversion','2DRobustBatching','data')
files = [ 'bg2data.rsf', 'bg2v.rsf', 'bg2v0.rsf', 'marmdata.rsf', 'marmv.rsf', 'marmv0.rsf', 'BG_DISCLAIMER.txt']

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

