import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}
# actuall ftp://ftp.slim.gatech.edu/data/SoftwareRelease/Modeling/AcousticTimeModeling/

loc = os.path.join('SoftwareRelease','Modeling','AcousticTimeModeling')
files = [ 'Water_Mar.mat' ]
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)


