import os
from rsf.proj import *

################
# RETRIEVE DATA
################

# Define SLIM FTP server information
FTPserver = {
             'server': 'ftp.slim.gatech.edu',
             'login': 'ftp',
             'password':''}

loc = os.path.join('SoftwareRelease','Acquisition','SourceSeparationLowRankHSS','Original')
files = ['data_zs10m.su', 'data_zs15m.su']


# Fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

End()

