fwi_params_struct = fwi_params('coarsen_model',false,...
                               'frequencies',3:6,...
                               'nfreq_cycles',1,...
                               'nopt_itr',3,...
                               'initialv_smooth',50,...
                               'optimization','sto_lbfgs',...
                               'modelname','overthrust_small');