import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','WaveformInversion','BasicTimeStepping','data')
files = ['delta.mat','epsilon.mat','theta.mat','v0.mat','v.mat']
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)
