import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc = os.path.join('SoftwareRelease','Processing','LowRankInterpolationAndDenoising','Regularization')
files = ['SuezShots125_355shots_Irreg.mat','irregpos.mat','regpos.mat']

# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)

End()
