import os
from rsf.proj import *

########################################################################
# RETRIEVE DATA
########################################################################
# define SLIM FTP server information
FTPserver = {
        'server': 'ftp.slim.gatech.edu',
        'login': 'ftp',
        'password':''}

loc   = os.path.join('SoftwareRelease','WaveformInversion','3DBatching','data')
files = ['edam_data.rsf','edam_m0.rsf','edam_mt.rsf','overthrust.rsf']
# fetch data from FTP server
for elm in files:
        Fetch(elm,loc,FTPserver)


